import { AvatarGenerator } from 'random-avatar-generator';

const generator = new AvatarGenerator();
export const players = [
  {
    id: '1',
    name: 'David Warner',
    bio: 'Batsmen With Highest Score',
    image: generator.generateRandomAvatar('David Warner'),
    role: 'Batsmen',
    country: 'Australia',
  },
  {
    id: '2',
    name: 'Rohit Sharma',
    bio: 'Batsmen With Most Runs',
    image: generator.generateRandomAvatar('Rohit Sharma'),
    role: 'Batsmen',
    country: 'India',
  },
  {
    id: '3',
    name: 'Shakib Al Hasan',
    bio: 'Batsmen With Best Batting Average',
    image: generator.generateRandomAvatar('Shakib Al Hasan'),
    role: 'Batsmen',
    country: 'Bangladesh',
  },
  {
    id: '4',
    name: 'Fabian Allen',
    bio: 'Batsmen With Best Strike Rate',
    image: generator.generateRandomAvatar('Fabian Allen'),
    role: 'Batsmen',
    country: 'West Indies',
  },
  {
    id: '5',
    name: 'Lasith Malinga',
    bio: 'Highest Wicket-Taker in T20Is',
    image: generator.generateRandomAvatar('Lasith Malinga'),
    role: 'Bowler',
    country: 'Sri Lanka',
  },
  {
    id: '6',
    name: 'Harbhajan Singh',
    bio: 'Off-Spinner From Punjab',
    image: generator.generateRandomAvatar('Harbhajan Singh'),
    role: 'Bowler',
    country: 'India',
  },
  {
    id: '7',
    name: 'Zaheer Khan',
    bio: "India's Leading Wicket-Taker",
    image: generator.generateRandomAvatar('Zaheer Khan'),
    role: 'Bowler',
    country: 'India',
  },
  {
    id: '8',
    name: 'Vernon Philander',
    bio: "South Africa's Best Bowler",
    image: generator.generateRandomAvatar('Vernon Philander'),
    role: 'Bowler',
    country: 'South Africa',
  },
  {
    id: '9',
    name: 'Chris Woakes',
    bio: "One Of England's Best All-Rounder",
    image: generator.generateRandomAvatar('Chris Woakes'),
    role: 'All-Rounder',
    country: 'England',
  },
  {
    id: '10',
    name: 'Rashid Khan',
    bio: "Afghanistan's Leading All-Rounder",
    image: generator.generateRandomAvatar('Rashid Khan'),
    role: 'All-Rounder',
    country: 'Afghanistan',
  },
  {
    id: '11',
    name: 'Mitchell Santner',
    bio: 'Best All-Rounder in New Zealand',
    image: generator.generateRandomAvatar('Mitchell Santner'),
    role: 'All-Rounder',
    country: 'New Zealand',
  },
  {
    id: '12',
    name: 'Imad Wasim',
    bio: "Pakistan's Best All-Rounder",
    image: generator.generateRandomAvatar('Imad Wasim'),
    role: 'All-Rounder',
    country: 'Pakistan',
  },
  {
    id: '13',
    name: 'Mark Boucher',
    bio: 'Leading Wicket Keeper',
    image: generator.generateRandomAvatar('Mark Boucher'),
    role: 'Wicket-Keeper',
    country: 'South Africa',
  },
  {
    id: '14',
    name: 'Adam Gilchrist',
    bio: "Australia's Best Wicket Keeper",
    image: generator.generateRandomAvatar('Adam Gilchrist'),
    role: 'Wicket-Keeper',
    country: 'Australia',
  },
];

export const playersCopy = [
  {
    id: '1',
    name: 'David Warner',
    bio: 'Batsmen With Highest Score',
    image: generator.generateRandomAvatar('David Warner'),
    role: 'Batsmen',
    country: 'Australia',
  },
  {
    id: '2',
    name: 'Rohit Sharma',
    bio: 'Batsmen With Most Runs',
    image: generator.generateRandomAvatar('Rohit Sharma'),
    role: 'Batsmen',
    country: 'India',
  },
  {
    id: '3',
    name: 'Shakib Al Hasan',
    bio: 'Batsmen With Best Batting Average',
    image: generator.generateRandomAvatar('Shakib Al Hasan'),
    role: 'Batsmen',
    country: 'Bangladesh',
  },
  {
    id: '4',
    name: 'Fabian Allen',
    bio: 'Batsmen With Best Strike Rate',
    image: generator.generateRandomAvatar('Fabian Allen'),
    role: 'Batsmen',
    country: 'West Indies',
  },
  {
    id: '5',
    name: 'Lasith Malinga',
    bio: 'Highest Wicket-Taker in T20Is',
    image: generator.generateRandomAvatar('Lasith Malinga'),
    role: 'Bowler',
    country: 'Sri Lanka',
  },
  {
    id: '6',
    name: 'Harbhajan Singh',
    bio: 'Off-Spinner From Punjab',
    image: generator.generateRandomAvatar('Harbhajan Singh'),
    role: 'Bowler',
    country: 'India',
  },
  {
    id: '7',
    name: 'Zaheer Khan',
    bio: "India's Leading Wicket-Taker",
    image: generator.generateRandomAvatar('Zaheer Khan'),
    role: 'Bowler',
    country: 'India',
  },
  {
    id: '8',
    name: 'Vernon Philander',
    bio: "South Africa's Best Bowler",
    image: generator.generateRandomAvatar('Vernon Philander'),
    role: 'Bowler',
    country: 'South Africa',
  },
  {
    id: '9',
    name: 'Chris Woakes',
    bio: "One Of England's Best All-Rounder",
    image: generator.generateRandomAvatar('Chris Woakes'),
    role: 'All-Rounder',
    country: 'England',
  },
  {
    id: '10',
    name: 'Rashid Khan',
    bio: "Afghanistan's Leading All-Rounder",
    image: generator.generateRandomAvatar('Rashid Khan'),
    role: 'All-Rounder',
    country: 'Afghanistan',
  },
  {
    id: '11',
    name: 'Mitchell Santner',
    bio: 'Best All-Rounder in New Zealand',
    image: generator.generateRandomAvatar('Mitchell Santner'),
    role: 'All-Rounder',
    country: 'New Zealand',
  },
  {
    id: '12',
    name: 'Imad Wasim',
    bio: "Pakistan's Best All-Rounder",
    image: generator.generateRandomAvatar('Imad Wasim'),
    role: 'All-Rounder',
    country: 'Pakistan',
  },
  {
    id: '13',
    name: 'Mark Boucher',
    bio: 'Leading Wicket Keeper',
    image: generator.generateRandomAvatar('Mark Boucher'),
    role: 'Wicket-Keeper',
    country: 'South Africa',
  },
  {
    id: '14',
    name: 'Adam Gilchrist',
    bio: "Australia's Best Wicket Keeper",
    image: generator.generateRandomAvatar('Adam Gilchrist'),
    role: 'Wicket-Keeper',
    country: 'Australia',
  },
];